
// This file has been generated by the GUI designer. Do not modify.
namespace ChatClient
{
	public partial class RegisterWindow
	{
		private global::Gtk.VBox VerticalBox;

		private global::Gtk.Label UsernameLabel;

		private global::Gtk.Entry UsernameIn;

		private global::Gtk.Label PasswordLabel1;

		private global::Gtk.Entry PasswordIn1;

		private global::Gtk.Label PasswordLabel2;

		private global::Gtk.Entry PasswordIn2;

		private global::Gtk.Label InfoDisplay;

		private global::Gtk.Button RegisterButton;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ChatClient.RegisterWindow
			this.Name = "ChatClient.RegisterWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("RegisterWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ChatClient.RegisterWindow.Gtk.Container+ContainerChild
			this.VerticalBox = new global::Gtk.VBox();
			this.VerticalBox.Name = "VerticalBox";
			this.VerticalBox.Homogeneous = true;
			this.VerticalBox.Spacing = 6;
			// Container child VerticalBox.Gtk.Box+BoxChild
			this.UsernameLabel = new global::Gtk.Label();
			this.UsernameLabel.Name = "UsernameLabel";
			this.UsernameLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Username");
			this.VerticalBox.Add(this.UsernameLabel);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.VerticalBox[this.UsernameLabel]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child VerticalBox.Gtk.Box+BoxChild
			this.UsernameIn = new global::Gtk.Entry();
			this.UsernameIn.CanFocus = true;
			this.UsernameIn.Name = "UsernameIn";
			this.UsernameIn.IsEditable = true;
			this.UsernameIn.InvisibleChar = '•';
			this.VerticalBox.Add(this.UsernameIn);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.VerticalBox[this.UsernameIn]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child VerticalBox.Gtk.Box+BoxChild
			this.PasswordLabel1 = new global::Gtk.Label();
			this.PasswordLabel1.Name = "PasswordLabel1";
			this.PasswordLabel1.LabelProp = global::Mono.Unix.Catalog.GetString("Password");
			this.VerticalBox.Add(this.PasswordLabel1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.VerticalBox[this.PasswordLabel1]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child VerticalBox.Gtk.Box+BoxChild
			this.PasswordIn1 = new global::Gtk.Entry();
			this.PasswordIn1.CanFocus = true;
			this.PasswordIn1.Name = "PasswordIn1";
			this.PasswordIn1.IsEditable = true;
			this.PasswordIn1.InvisibleChar = '•';
			this.VerticalBox.Add(this.PasswordIn1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.VerticalBox[this.PasswordIn1]));
			w4.Position = 3;
			w4.Expand = false;
			w4.Fill = false;
			// Container child VerticalBox.Gtk.Box+BoxChild
			this.PasswordLabel2 = new global::Gtk.Label();
			this.PasswordLabel2.Name = "PasswordLabel2";
			this.PasswordLabel2.LabelProp = global::Mono.Unix.Catalog.GetString("Re-enter Password");
			this.VerticalBox.Add(this.PasswordLabel2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.VerticalBox[this.PasswordLabel2]));
			w5.Position = 4;
			w5.Expand = false;
			w5.Fill = false;
			// Container child VerticalBox.Gtk.Box+BoxChild
			this.PasswordIn2 = new global::Gtk.Entry();
			this.PasswordIn2.CanFocus = true;
			this.PasswordIn2.Name = "PasswordIn2";
			this.PasswordIn2.IsEditable = true;
			this.PasswordIn2.InvisibleChar = '•';
			this.VerticalBox.Add(this.PasswordIn2);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.VerticalBox[this.PasswordIn2]));
			w6.Position = 5;
			w6.Expand = false;
			w6.Fill = false;
			// Container child VerticalBox.Gtk.Box+BoxChild
			this.InfoDisplay = new global::Gtk.Label();
			this.InfoDisplay.Name = "InfoDisplay";
			this.VerticalBox.Add(this.InfoDisplay);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.VerticalBox[this.InfoDisplay]));
			w7.Position = 6;
			w7.Expand = false;
			w7.Fill = false;
			// Container child VerticalBox.Gtk.Box+BoxChild
			this.RegisterButton = new global::Gtk.Button();
			this.RegisterButton.CanFocus = true;
			this.RegisterButton.Name = "RegisterButton";
			this.RegisterButton.UseUnderline = true;
			this.RegisterButton.Label = global::Mono.Unix.Catalog.GetString("Register");
			this.VerticalBox.Add(this.RegisterButton);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.VerticalBox[this.RegisterButton]));
			w8.Position = 7;
			w8.Expand = false;
			w8.Fill = false;
			this.Add(this.VerticalBox);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
			this.RegisterButton.Clicked += new global::System.EventHandler(this.OnRegisterButtonClicked);
		}
	}
}
