
// This file has been generated by the GUI designer. Do not modify.
namespace ChatClient
{
	public partial class LobbyWindow
	{
		private global::Gtk.Alignment alignment1;

		private global::Gtk.VBox vbox8;

		private global::Gtk.EventBox eventbox2;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.VBox vbox4;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Button makeRoomButton;

		private global::Gtk.Button joinRoomButton;

		private global::Gtk.Button button3;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ChatClient.LobbyWindow
			this.Name = "ChatClient.LobbyWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("LobbyWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ChatClient.LobbyWindow.Gtk.Container+ContainerChild
			this.alignment1 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			this.alignment1.LeftPadding = ((uint)(25));
			this.alignment1.TopPadding = ((uint)(25));
			this.alignment1.RightPadding = ((uint)(25));
			this.alignment1.BottomPadding = ((uint)(25));
			// Container child alignment1.Gtk.Container+ContainerChild
			this.vbox8 = new global::Gtk.VBox();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.eventbox2 = new global::Gtk.EventBox();
			this.eventbox2.Name = "eventbox2";
			// Container child eventbox2.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			global::Gtk.Viewport w1 = new global::Gtk.Viewport();
			w1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			w1.Add(this.vbox4);
			this.GtkScrolledWindow.Add(w1);
			this.eventbox2.Add(this.GtkScrolledWindow);
			this.vbox8.Add(this.eventbox2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.eventbox2]));
			w5.Position = 0;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Homogeneous = true;
			this.hbox3.Spacing = 45;
			// Container child hbox3.Gtk.Box+BoxChild
			this.makeRoomButton = new global::Gtk.Button();
			this.makeRoomButton.CanFocus = true;
			this.makeRoomButton.Name = "makeRoomButton";
			this.makeRoomButton.UseUnderline = true;
			this.makeRoomButton.Label = global::Mono.Unix.Catalog.GetString("Room Creation");
			this.hbox3.Add(this.makeRoomButton);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.makeRoomButton]));
			w6.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.joinRoomButton = new global::Gtk.Button();
			this.joinRoomButton.WidthRequest = 0;
			this.joinRoomButton.CanFocus = true;
			this.joinRoomButton.Name = "joinRoomButton";
			this.joinRoomButton.UseUnderline = true;
			this.joinRoomButton.Label = global::Mono.Unix.Catalog.GetString("Join");
			this.hbox3.Add(this.joinRoomButton);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.joinRoomButton]));
			w7.Position = 1;
			// Container child hbox3.Gtk.Box+BoxChild
			this.button3 = new global::Gtk.Button();
			this.button3.CanFocus = true;
			this.button3.Name = "button3";
			this.button3.UseUnderline = true;
			this.button3.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
			this.hbox3.Add(this.button3);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.button3]));
			w8.Position = 2;
			this.vbox8.Add(this.hbox3);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox3]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			this.alignment1.Add(this.vbox8);
			this.Add(this.alignment1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 550;
			this.DefaultHeight = 550;
			this.Show();
			this.joinRoomButton.Clicked += new global::System.EventHandler(this.OnJoinRoomButtonClicked);
		}
	}
}
