
// This file has been generated by the GUI designer. Do not modify.
namespace ChatClient
{
	public partial class RoomWindow
	{
		private global::Gtk.Alignment alignment;

		private global::Gtk.VBox vboxWindow;

		private global::Gtk.Label titleLabel;

		private global::Gtk.ScrolledWindow scrolledMessageWindow;

		private global::Gtk.VBox vboxMessages;

		private global::Gtk.HBox hboxSendMessages;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TextView sendMessageText;

		private global::Gtk.Button sendMessageButton;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ChatClient.RoomWindow
			this.Name = "ChatClient.RoomWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("RoomWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ChatClient.RoomWindow.Gtk.Container+ContainerChild
			this.alignment = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment.Name = "alignment";
			this.alignment.LeftPadding = ((uint)(10));
			this.alignment.TopPadding = ((uint)(10));
			this.alignment.RightPadding = ((uint)(10));
			this.alignment.BottomPadding = ((uint)(10));
			// Container child alignment.Gtk.Container+ContainerChild
			this.vboxWindow = new global::Gtk.VBox();
			this.vboxWindow.Name = "vboxWindow";
			this.vboxWindow.Spacing = 6;
			// Container child vboxWindow.Gtk.Box+BoxChild
			this.titleLabel = new global::Gtk.Label();
			this.titleLabel.Name = "titleLabel";
			this.titleLabel.LabelProp = global::Mono.Unix.Catalog.GetString("asdf");
			this.vboxWindow.Add(this.titleLabel);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vboxWindow[this.titleLabel]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vboxWindow.Gtk.Box+BoxChild
			this.scrolledMessageWindow = new global::Gtk.ScrolledWindow();
			this.scrolledMessageWindow.CanFocus = true;
			this.scrolledMessageWindow.Name = "scrolledMessageWindow";
			this.scrolledMessageWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledMessageWindow.Gtk.Container+ContainerChild
			global::Gtk.Viewport w2 = new global::Gtk.Viewport();
			w2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.vboxMessages = new global::Gtk.VBox();
			this.vboxMessages.Name = "vboxMessages";
			this.vboxMessages.Spacing = 6;
			w2.Add(this.vboxMessages);
			this.scrolledMessageWindow.Add(w2);
			this.vboxWindow.Add(this.scrolledMessageWindow);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vboxWindow[this.scrolledMessageWindow]));
			w5.Position = 1;
			// Container child vboxWindow.Gtk.Box+BoxChild
			this.hboxSendMessages = new global::Gtk.HBox();
			this.hboxSendMessages.HeightRequest = 0;
			this.hboxSendMessages.Name = "hboxSendMessages";
			this.hboxSendMessages.Spacing = 6;
			// Container child hboxSendMessages.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.HeightRequest = 1;
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.sendMessageText = new global::Gtk.TextView();
			this.sendMessageText.CanFocus = true;
			this.sendMessageText.Name = "sendMessageText";
			this.GtkScrolledWindow.Add(this.sendMessageText);
			this.hboxSendMessages.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hboxSendMessages[this.GtkScrolledWindow]));
			w7.Position = 0;
			// Container child hboxSendMessages.Gtk.Box+BoxChild
			this.sendMessageButton = new global::Gtk.Button();
			this.sendMessageButton.CanFocus = true;
			this.sendMessageButton.Name = "sendMessageButton";
			this.sendMessageButton.UseUnderline = true;
			this.sendMessageButton.Label = global::Mono.Unix.Catalog.GetString("Send");
			this.hboxSendMessages.Add(this.sendMessageButton);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hboxSendMessages[this.sendMessageButton]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			this.vboxWindow.Add(this.hboxSendMessages);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vboxWindow[this.hboxSendMessages]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			this.alignment.Add(this.vboxWindow);
			this.Add(this.alignment);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
			this.sendMessageButton.Clicked += new global::System.EventHandler(this.OnSendMessageButtonClicked);
		}
	}
}
