
// This file has been generated by the GUI designer. Do not modify.
namespace ChatClient
{
	public partial class LobbyWindow
	{
		private global::Gtk.Alignment alignment1;

		private global::Gtk.EventBox eventbox2;

		private global::Gtk.VBox vbox3;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ChatClient.LobbyWindow
			this.Name = "ChatClient.LobbyWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("LobbyWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ChatClient.LobbyWindow.Gtk.Container+ContainerChild
			this.alignment1 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			this.alignment1.LeftPadding = ((uint)(25));
			this.alignment1.TopPadding = ((uint)(25));
			this.alignment1.RightPadding = ((uint)(25));
			this.alignment1.BottomPadding = ((uint)(25));
			// Container child alignment1.Gtk.Container+ContainerChild
			this.eventbox2 = new global::Gtk.EventBox();
			this.eventbox2.Name = "eventbox2";
			// Container child eventbox2.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			this.eventbox2.Add(this.vbox3);
			this.alignment1.Add(this.eventbox2);
			this.Add(this.alignment1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 550;
			this.DefaultHeight = 550;
			this.Show();
		}
	}
}
