
// This file has been generated by the GUI designer. Do not modify.
namespace ChatClient
{
	public partial class MakeRoomWindow
	{
		private global::Gtk.VBox vbox5;

		private global::Gtk.Label TitleLabe;

		private global::Gtk.Label RoomNameLabel;

		private global::Gtk.Entry RoomNameIn;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Button MakeRoomButton;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TextView DescriptionBox;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget ChatClient.MakeRoomWindow
			this.Name = "ChatClient.MakeRoomWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("MakeRoomWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			this.AllowGrow = false;
			this.DefaultWidth = 0;
			this.DefaultHeight = 200;
			// Container child ChatClient.MakeRoomWindow.Gtk.Container+ContainerChild
			this.vbox5 = new global::Gtk.VBox();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.TitleLabe = new global::Gtk.Label();
			this.TitleLabe.Name = "TitleLabe";
			this.TitleLabe.LabelProp = global::Mono.Unix.Catalog.GetString("Room Creator");
			this.vbox5.Add(this.TitleLabe);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.TitleLabe]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.RoomNameLabel = new global::Gtk.Label();
			this.RoomNameLabel.Name = "RoomNameLabel";
			this.RoomNameLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Room Name");
			this.vbox5.Add(this.RoomNameLabel);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.RoomNameLabel]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.RoomNameIn = new global::Gtk.Entry();
			this.RoomNameIn.CanFocus = true;
			this.RoomNameIn.Name = "RoomNameIn";
			this.RoomNameIn.IsEditable = true;
			this.RoomNameIn.InvisibleChar = '•';
			this.vbox5.Add(this.RoomNameIn);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.RoomNameIn]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Homogeneous = true;
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.MakeRoomButton = new global::Gtk.Button();
			this.MakeRoomButton.CanFocus = true;
			this.MakeRoomButton.Name = "MakeRoomButton";
			this.MakeRoomButton.UseUnderline = true;
			this.MakeRoomButton.Label = global::Mono.Unix.Catalog.GetString("Create Room");
			this.hbox1.Add(this.MakeRoomButton);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.MakeRoomButton]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox5.Add(this.hbox1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox1]));
			w5.Position = 3;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.DescriptionBox = new global::Gtk.TextView();
			this.DescriptionBox.CanFocus = true;
			this.DescriptionBox.Name = "DescriptionBox";
			this.DescriptionBox.Editable = false;
			this.DescriptionBox.CursorVisible = false;
			this.DescriptionBox.AcceptsTab = false;
			this.GtkScrolledWindow.Add(this.DescriptionBox);
			this.vbox5.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.GtkScrolledWindow]));
			w7.Position = 4;
			this.Add(this.vbox5);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Show();
		}
	}
}
