
// This file has been generated by the GUI designer. Do not modify.

public partial class LoginWindow
{
	private global::Gtk.VBox vbox3;

	private global::Gtk.Label LoginLabel;

	private global::Gtk.Label display;

	private global::Gtk.Alignment alignment3;

	private global::Gtk.Entry loginIn;

	private global::Gtk.Button login;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget LoginWindow
		this.WidthRequest = 150;
		this.HeightRequest = 200;
		this.Name = "LoginWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("LoginWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.DefaultWidth = 150;
		this.DefaultHeight = 200;
		// Container child LoginWindow.Gtk.Container+ContainerChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.WidthRequest = 150;
		this.vbox3.HeightRequest = 200;
		this.vbox3.Name = "vbox3";
		this.vbox3.Homogeneous = true;
		this.vbox3.Spacing = 1;
		this.vbox3.BorderWidth = ((uint)(3));
		// Container child vbox3.Gtk.Box+BoxChild
		this.LoginLabel = new global::Gtk.Label();
		this.LoginLabel.Name = "LoginLabel";
		this.LoginLabel.Yalign = 0F;
		this.LoginLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Enter Username");
		this.vbox3.Add(this.LoginLabel);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.LoginLabel]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		w1.Padding = ((uint)(50));
		// Container child vbox3.Gtk.Box+BoxChild
		this.display = new global::Gtk.Label();
		this.display.Name = "display";
		this.vbox3.Add(this.display);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.display]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.alignment3 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
		this.alignment3.Name = "alignment3";
		this.alignment3.LeftPadding = ((uint)(50));
		this.alignment3.RightPadding = ((uint)(50));
		// Container child alignment3.Gtk.Container+ContainerChild
		this.loginIn = new global::Gtk.Entry();
		this.loginIn.CanFocus = true;
		this.loginIn.Name = "loginIn";
		this.loginIn.IsEditable = true;
		this.loginIn.InvisibleChar = '•';
		this.alignment3.Add(this.loginIn);
		this.vbox3.Add(this.alignment3);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.alignment3]));
		w4.Position = 2;
		w4.Expand = false;
		w4.Fill = false;
		w4.Padding = ((uint)(40));
		// Container child vbox3.Gtk.Box+BoxChild
		this.login = new global::Gtk.Button();
		this.login.WidthRequest = 30;
		this.login.HeightRequest = 0;
		this.login.CanFocus = true;
		this.login.Name = "login";
		this.login.UseUnderline = true;
		this.login.BorderWidth = ((uint)(50));
		this.login.Label = global::Mono.Unix.Catalog.GetString("Login");
		this.vbox3.Add(this.login);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.login]));
		w5.Position = 3;
		w5.Expand = false;
		w5.Fill = false;
		this.Add(this.vbox3);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.loginIn.KeyPressEvent += new global::Gtk.KeyPressEventHandler(this.KeyPress);
		this.login.Clicked += new global::System.EventHandler(this.Login);
	}
}
