
// This file has been generated by the GUI designer. Do not modify.

public partial class LoginWindow
{
	private global::Gtk.VBox vbox3;

	private global::Gtk.Label LoginLabel;

	private global::Gtk.Entry loginIn;

	private global::Gtk.Label PasswordLabel;

	private global::Gtk.Entry passwordIn;

	private global::Gtk.Label display;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Button login;

	private global::Gtk.Button RegisterButton;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget LoginWindow
		this.WidthRequest = 150;
		this.HeightRequest = 200;
		this.Name = "LoginWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("LoginWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.DefaultWidth = 150;
		this.DefaultHeight = 200;
		// Container child LoginWindow.Gtk.Container+ContainerChild
		this.vbox3 = new global::Gtk.VBox();
		this.vbox3.WidthRequest = 150;
		this.vbox3.HeightRequest = 200;
		this.vbox3.Name = "vbox3";
		this.vbox3.Homogeneous = true;
		this.vbox3.Spacing = 1;
		this.vbox3.BorderWidth = ((uint)(3));
		// Container child vbox3.Gtk.Box+BoxChild
		this.LoginLabel = new global::Gtk.Label();
		this.LoginLabel.Name = "LoginLabel";
		this.LoginLabel.Yalign = 0F;
		this.LoginLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Enter Username");
		this.vbox3.Add(this.LoginLabel);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.LoginLabel]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		w1.Padding = ((uint)(50));
		// Container child vbox3.Gtk.Box+BoxChild
		this.loginIn = new global::Gtk.Entry();
		this.loginIn.CanFocus = true;
		this.loginIn.Name = "loginIn";
		this.loginIn.IsEditable = true;
		this.loginIn.InvisibleChar = '•';
		this.vbox3.Add(this.loginIn);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.loginIn]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.PasswordLabel = new global::Gtk.Label();
		this.PasswordLabel.Name = "PasswordLabel";
		this.PasswordLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Enter Password");
		this.vbox3.Add(this.PasswordLabel);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.PasswordLabel]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.passwordIn = new global::Gtk.Entry();
		this.passwordIn.CanFocus = true;
		this.passwordIn.Name = "passwordIn";
		this.passwordIn.IsEditable = true;
		this.passwordIn.Visibility = false;
		this.passwordIn.InvisibleChar = '•';
		this.vbox3.Add(this.passwordIn);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.passwordIn]));
		w4.Position = 3;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.display = new global::Gtk.Label();
		this.display.Name = "display";
		this.vbox3.Add(this.display);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.display]));
		w5.Position = 4;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Homogeneous = true;
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.login = new global::Gtk.Button();
		this.login.HeightRequest = 0;
		this.login.CanFocus = true;
		this.login.Name = "login";
		this.login.Label = global::Mono.Unix.Catalog.GetString("Login");
		this.hbox1.Add(this.login);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.login]));
		w6.Position = 0;
		w6.Padding = ((uint)(10));
		// Container child hbox1.Gtk.Box+BoxChild
		this.RegisterButton = new global::Gtk.Button();
		this.RegisterButton.CanFocus = true;
		this.RegisterButton.Name = "RegisterButton";
		this.RegisterButton.UseUnderline = true;
		this.RegisterButton.Label = global::Mono.Unix.Catalog.GetString("Register");
		this.hbox1.Add(this.RegisterButton);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.RegisterButton]));
		w7.Position = 1;
		w7.Padding = ((uint)(10));
		this.vbox3.Add(this.hbox1);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox1]));
		w8.Position = 6;
		w8.Expand = false;
		w8.Fill = false;
		this.Add(this.vbox3);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.loginIn.KeyPressEvent += new global::Gtk.KeyPressEventHandler(this.KeyPress);
		this.login.Clicked += new global::System.EventHandler(this.Login);
		this.RegisterButton.Clicked += new global::System.EventHandler(this.OnRegisterButtonClicked);
	}
}
